language: go

go: 1.4.2

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-python
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-python

install:
  - sudo curl -Lo /tmp/srclib.gz https://srclib-release.s3.amazonaws.com/srclib/0.1.1-no-docker5/linux-amd64/srclib.gz 
  - sudo gunzip -f /tmp/srclib.gz -r /usr/local/bin
  - sudo chmod +x /usr/local/bin/srclib
  - mkdir -p $HOME/.srclib/sourcegraph.com/sourcegraph/
  - ln -s $TRAVIS_BUILD_DIR $HOME/.srclib/sourcegraph.com/sourcegraph/srclib-python
  - make install

# TODO(sqs): add `go test`
script:
  - srclib test 
